/* Generated By:JavaCC: Do not edit this line. AplParserConstants.java */
package com.mlt.japl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNC = 5;
  /** RegularExpression Id. */
  int OUTERPROD = 6;
  /** RegularExpression Id. */
  int MONADICOPERATOR = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int CONSTANT = 9;
  /** RegularExpression Id. */
  int CPLXCONSTANT = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int SIGN = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int STRINGDELIM = 15;
  /** RegularExpression Id. */
  int STRINGCHAR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<FUNC>",
    "\"\\u2218.\"",
    "<MONADICOPERATOR>",
    "<ID>",
    "<CONSTANT>",
    "<CPLXCONSTANT>",
    "<STRING>",
    "<NUMBER>",
    "<SIGN>",
    "<DIGIT>",
    "<STRINGDELIM>",
    "<STRINGCHAR>",
    "\"\\u22c4\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\u2190\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
  };

}
