/* Generated By:JavaCC: Do not edit this line. AplParserConstants.java */
package com.mlt.japl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNC = 6;
  /** RegularExpression Id. */
  int OUTERPROD = 7;
  /** RegularExpression Id. */
  int MONADICOPERATOR = 8;
  /** RegularExpression Id. */
  int STMTSEPARATOR = 9;
  /** RegularExpression Id. */
  int STMTSEP = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int CONSTANT = 12;
  /** RegularExpression Id. */
  int CPLXCONSTANT = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int SIGN = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int STRINGDELIM = 18;
  /** RegularExpression Id. */
  int STRINGCHAR = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<FUNC>",
    "\"\\u2218.\"",
    "<MONADICOPERATOR>",
    "\";\"",
    "<STMTSEP>",
    "<ID>",
    "<CONSTANT>",
    "<CPLXCONSTANT>",
    "<STRING>",
    "<NUMBER>",
    "<SIGN>",
    "<DIGIT>",
    "<STRINGDELIM>",
    "<STRINGCHAR>",
    "\"(\"",
    "\")\"",
    "\":If\"",
    "\":Then\"",
    "\":Else\"",
    "\":EndIf\"",
    "\":While\"",
    "\":Do\"",
    "\":EndWhile\"",
    "\":Repeat\"",
    "\":EndRepeat\"",
    "\"[\"",
    "\"]\"",
    "\"\\u2190\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
  };

}
